FROM java:8
MAINTAINER hello-docker
WORKDIR /
# hello-docker-0.0.1-SNAPSHOT.jar为maven打包生成的，app.jar是被打进镜像中jar
ADD target/hello-docker-0.0.1-SNAPSHOT.jar app.jar
# 对外暴露的端口
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app.jar"]